# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now we have gathered all the required skills needed to solve systems of linear equations. We saw why need to calculate inverses of matrices, followed by matrix multiplication to figure the values of unknown variables. 

Following exercises present some problems that can be converted into a system of linear equations. Solve the problems for the values of unknown variables. 

## Objectives
You will be able to:

* Build a system of equations from given problem by creating matrix and vectors in NumPy
* Calculate the inverse and dot-product to get the values for unknown variables.
* Solve linear equations using `numpy.linalg.solve()`

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea was sold, giving a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [110]:
import numpy as np

# Solution:
# x = coffee
# y = tea

# matrix versions of day_1 and day_2: 
A = np.array([[29, 41], [23,41]]) # 2x2 matrix
B = np.array([[490, 448]]) # 1x2 matrix

# take inverse of matrix_inputs to isolate each variable
A_inv = np.linalg.inv(A) # 2x2 matrix

# take the dot product because you need to multiply both sides by the inverse
# you have to transpose B in order to take its dot product because it's a 1x2 matrix while A is a 2x2 matrix
A_inv.dot(B.T) # 2x1 matrix

# using the solve method to confirm you did the dot method correctly
# keep B transposed
np.linalg.solve(A,B.T)


array([[7.],
       [7.]])

In [13]:
# Explain your answer in terms of prices


## Exercise 2:

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in another music concert. 

How much was the admission for each child and adult?

In [104]:
# Create a system of equations

# matrices
A = np.array([[12,3], [8,3]]) # 2x2 matrix
B = np.array([162, 122]) # 2 matrix

# inverse
inv_A = np.linalg.inv(A) # 2x2 matrix


# dot product
# don't have to transpose here because the # of columns in the 1st matrix equals the # of rows in the 2nd matrix
inv_A.dot(B) # 2 matrix

# solve method to check
np.linalg.solve(A,B)


(2,)

In [7]:
# Describe your result


## Exercise 3:

You want to make a certain kind of tropical punch, using bananas, oranges, and papayas. 

Suppose you don't know how many of each to put in the punch, but you know that there are seven pieces of fruit in the mix, and there are twice as many oranges as bananas. 

You also know that the seven pieces of fruit cost \$5.25, 

where bananas cost \$.50 each, oranges cost \$.75 each, and papayas cost \$1.25 each.

How many bananas, oranges and papayas would you need to make this punch ?

In [125]:
# Create a system of equations
A = np.array([[1,1,1],[0.5, 0.75, 1.25], [-2,1,0]]) # how do you know to take the inverse of this matrix?
B = np.array([[7, 5.25, 0]])  # 3 matrix

# inverse of A
A_inv = np.linalg.inv(A) # 3x3 matrix

# dot product
A_inv.dot(B.T) # 3 matrix

# solve method
np.linalg.solve(A,B.T)

# A_inv.shape

array([[2.],
       [4.],
       [1.]])

In [2]:
# Explain your answer


## Exercise 4

A landlord owns 3 houses, a 1-bedroom, a 2-bedroom , and a 3-bedroom house. 

The total rent he receives is 1240 dollars. 

He needs to make some repairs, where it costs 10% of the 1-bedroom house’s rent for its repairs, 20% of the 2-bedroom for its repairs, and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was $276. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [134]:
# Create a system of equations
A = np.matrix([[1,1,1],[0.1, 0.2, 0.3], [2,0,-1]])
B = np.matrix([1240, 276, 0]) # 1x3 matrix

# inverse of A
inv_A = np.linalg.inv(A) # 3x3 matrix

# dot product
inv_A.dot(B.T) 

# solve method
np.linalg.solve(A,B.T)


matrix([[280.],
        [400.],
        [560.]])

In [11]:
# Explain your answer


## Summary
In this lab, we saw how to use Numpy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `.solve()`. We shall now take these skills forward and see how we can define a simple regression problem using linear algebra and solve it with numpy, only using the skills that we have learnt so far. 